name: BS2024 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Compiler Setup
      run: sudo apt-get install -y gcc make

    - name: Compile programs
      run: |
          for dir in $(find . -type f -name '*.c' -exec dirname {} \; | sort -u); do
            for file in $dir/*.c; do
              base=$(basename "$file" .c)
              echo "Compiling $file"
              gcc -std=c11 -pedantic -D_XOPEN_SOURCE=700 -Wall -Werror -o "$dir/$base" "$file" || echo "Failed to compile $file"
            done
          don
      
