name: BS2024 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Compiler Setup
      run: sudo apt-get install -y gcc make

    - name: Compile programs
      run: |
          # Find all directories containing .c files
          while IFS= read -r -d '' dir; do
            echo "Compiling programs in $dir"
            if [ -f "$dir/make" ]; then
              echo "Running makefile."
              make -C "$dir" || echo "Failed to build using makefile in $dir"
            else
            
              while IFS= read -r -d '' file; do
                base=$(basename "$file" .c)
                echo "Compiling $file"
                gcc -std=c11 -pedantic -D_XOPEN_SOURCE=700 -Wall -Werror -o "$dir/$base" "$file" || echo "Failed to compile $file"
              done < <(find "$dir" -type f -name '*.c' -print0)
            fi
          done < <(find . -type f -name '*.c' -exec dirname {} \; | sort -u | uniq | xargs -0 -I {} echo {} | tr '\n' '\0')
